version: "3.9"

services:
  web:
    build: .
    command: gunicorn fantasy_football_league.wsgi:application --bind 0.0.0.0:8000 --workers 3 --log-level info
    environment:
      DJANGO_ENV: production
      DEBUG: "0"
      DB_NAME: fantasy_football
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fantasy_football
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
