version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000  # Dev server
    volumes:
      - .:/apps  # Hot reload for dev
    ports:
      - "8000:8000"
    environment:
      DJANGO_ENV: development
      DEBUG: "1"
      DB_NAME: fantasy_football
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fantasy_football
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
