# Generated by Django 5.2.6 on 2025-09-19 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0002_alter_player_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={},
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["team", "position"], name="league_play_team_id_31b739_idx"
            ),
        ),
    ]
