# Generated by Django 5.2.6 on 2025-09-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0003_alter_player_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
